let words = [
    {
        "id":1,
        "image":"img/bank.jpg",
        "caption":"Bank",
        "text": "/bæŋk/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/bank-us.mp3",
    },
    {
        "id":2,
        "image":"img/bus_station.png",
        "caption":"Bus station",
        "text": "/ˈsteɪʃən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/station-au.mp3",
    },
    {
        "id":3,
        "image":"img/cafe.jpg",
        "caption":"Cafe",
        "text": "/ˈkæfeɪ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cafe-us.mp3",
    },
    {
        "id":4,
        "image":"img/hospital.png",
        "caption":"Hospital",
        "text": "/ˈhɒs.pɪ.tl̩/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/hospital-uk.mp3",
    },
    {
        "id":5,
        "image":"img/museum.png",
        "caption":"Museum",
        "text": "/mjuˈzi.əm/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/museum-us.mp3",
    },
    {
        "id":6,
        "image":"img/playground.jpg",
        "caption":"Playground",
        "text": "/ˈpleɪɡɹaʊnd/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/playground-us.mp3",
    },
    {
        "id":7,
        "image":"img/post_office.png",
        "caption":"Post office",
        "text": "/poʊst/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/post-us.mp3",
    },
    {
        "id":8,
        "image":"img/school.png",
        "caption":"School",
        "text": "/skuːl/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/school-uk.mp3",
    },
    {
        "id":9,
        "image":"img/shop.png",
        "caption":"Shop",
        "text": "/ʃɑp/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/shop-us.mp3",
    },
    {
        "id":10,
        "image":"img/skyscraper.jpg",
        "caption":"Skyscraper",
    },
    {
        "id":11,
        "image":"img/street.jpg",
        "caption":"Street",
        "text": "/stɹiːt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/street-uk.mp3",
    },
    {
        "id":12,
        "image":"img/train_station.jpg",
        "caption":"Train station",
        "text": "/ˈsteɪʃən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/station-au.mp3",
    }
]