let words = [
    {
        "id":1,
        "image":"img/apple.png",
        "caption":"Apple",
        "text": "/ˈæp.əl/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/apple-us.mp3",
    },
    {
        "id":1,
        "image":"img/apricot.png",
        "caption":"Apricot",
        "text": "/æepɹɪˈkɒt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/apricot-au.mp3",
    },
    {
        "id":3,
        "image":"img/banana.jpg",
        "caption":"Banana",
        "text": "/bəˈnɑːnə/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/banana-uk.mp3",
    },
    {
        "id":4,
        "image":"img/cherry.jpg",
        "caption":"Cherry",
        "text": "/ˈt͡ʃɛɹi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cherry-uk.mp3",
    },
    {
        "id":5,
        "image":"img/fig.jpg",
        "caption":"Fig",
        "text": "/fɪɡ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/fig-us.mp3",
    },
    {
        "id":6,
        "image":"img/kiwi.jpg",
        "caption":"Kiwi",
        "text": "/ˈkiːwi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/kiwi-au.mp3",
    },
    {
        "id":7,
        "image":"img/lemon.jpg",
        "caption":"Lemon",
        "text": "/ˈlɛmən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/lemon-uk.mp3",
    },
    {
        "id":8,
        "image":"img/melon.jpg",
        "caption":"Melon",
        "text": "/ˈmɛlən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/melon-us.mp3",
    },
    {
        "id":9,
        "image":"img/peach.jpg",
        "caption":"Peach",
        "text": "/piːt͡ʃ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/peach-us.mp3",
    },
    {
        "id":10,
        "image":"img/plum.jpg",
        "caption":"Plum",
        "text": "/plʌm/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/plum-us.mp3",
    },
    {
        "id":11,
        "image":"img/pomegranate.jpg",
        "caption":"Pomegranate",
        "text": "/ˈpɒm.ɪˌɡɹæn.ɪt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/pomegranate-uk.mp3",
    },
    {
        "id":12,
        "image":"img/watermelon.jpg",
        "caption":"Watermelon",
        "text": "/ˈwɔtəɹˌmɛlən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/watermelon-us.mp3",
    }
]