let fruits = [
    {
        "id":1,
        "image":"img/apple.png",
        "caption":"Apple",
    },
    {
        "id":1,
        "image":"img/apricot.jpg",
        "caption":"Apricot",
    },
    {
        "id":3,
        "image":"img/banana.jpg",
        "caption":"Banana",
    },
    {
        "id":4,
        "image":"img/cherry.jpg",
        "caption":"Cherry",
    },
    {
        "id":5,
        "image":"img/fig.jpg",
        "caption":"Fig",
    },
    {
        "id":6,
        "image":"img/kiwi.jpg",
        "caption":"Kiwi",
    },
    {
        "id":7,
        "image":"img/lemon.jpg",
        "caption":"Lemon",
    },
    {
        "id":8,
        "image":"img/melon.jpg",
        "caption":"Melon",
    },
    {
        "id":9,
        "image":"img/orange.jpg",
        "caption":"Orange",
    },
    {
        "id":10,
        "image":"img/peach.jpg",
        "caption":"Peach",
    },
    {
        "id":11,
        "image":"img/pomegranate.jpg",
        "caption":"Pomegranate",
    },
    {
        "id":12,
        "image":"img/watermelon.jpg",
        "caption":"Watermelon",
    }
]