let words = [
    {
        "id":1,
        "image":"img/bay.jpg",
        "caption":"Bay",
    },
    {
        "id":2,
        "image":"img/beach.jpg",
        "caption":"Beach",
    },
    {
        "id":3,
        "image":"img/canal.jpg",
        "caption":"Canal",
    },
    {
        "id":4,
        "image":"img/canyon.jpg",
        "caption":"Canyon",
    },
    {
        "id":5,
        "image":"img/desert.jpg",
        "caption":"Desert",
    },
    {
        "id":6,
        "image":"img/island.jpg",
        "caption":"Island",
    },
    {
        "id":7,
        "image":"img/lake.jpg",
        "caption":"Lake",
    },
    {
        "id":8,
        "image":"img/meadow.jpg",
        "caption":"Meadow",
    },
    {
        "id":9,
        "image":"img/mountain.jpg",
        "caption":"Mountains",
    },
    {
        "id":10,
        "image":"img/ocean.jpg",
        "caption":"Ocean",
    },
    {
        "id":11,
        "image":"img/valley.jpg",
        "caption":"Valley",
    },
    {
        "id":12,
        "image":"img/waterfall.jpg",
        "caption":"Waterfall",
    }
]