let words = [
    {
        "id":1,
        "image":"img/bay.jpg",
        "caption":"Bay",
        "text": "/beɪ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/bay-us.mp3",
    },
    {
        "id":2,
        "image":"img/beach.jpg",
        "caption":"Beach",
        "text": "/biːt͡ʃ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/beach-uk.mp3",
    },
    {
        "id":3,
        "image":"img/canal.jpg",
        "caption":"Canal",
        "text": "/kəˈnæl/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/canal-uk.mp3",
    },
    {
        "id":4,
        "image":"img/cliff.jpg",
        "caption":"Cliff",
        "text": "/klɪf/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cliff-us.mp3",
    },
    {
        "id":5,
        "image":"img/desert.jpg",
        "caption":"Desert",
        "text": "/dɪˈzɜːt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/desert-1-uk.mp3",
    },
    {
        "id":6,
        "image":"img/island.jpg",
        "caption":"Island",
        "text": "/ˈaɪ̯lənd/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/island-uk.mp3",
    },
    {
        "id":7,
        "image":"img/lake.jpg",
        "caption":"Lake",
        "text": "/leɪk/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/lake-uk.mp3",
    },
    {
        "id":8,
        "image":"img/meadow.jpg",
        "caption":"Meadow",
        "text": "/ˈmɛdoʊ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/meadow-us.mp3",
    },
    {
        "id":9,
        "image":"img/mountain.jpg",
        "caption":"Mountains",
        "text": "/ˈmaʊntɪn/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/mountain-uk.mp3",
    },
    {
        "id":10,
        "image":"img/ocean.jpg",
        "caption":"Ocean",
        "text": "/ˈoʊ.ʃən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/ocean-us.mp3",
    },
    {
        "id":11,
        "image":"img/valley.jpg",
        "caption":"Valley",
        "text": "/ˈvæli/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/valley-uk.mp3",
    },
    {
        "id":12,
        "image":"img/waterfall.jpg",
        "caption":"Waterfall",
        "text": "/ˈwɔtɚfɔl/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/waterfall-us.mp3",
    }
]