let words = [
    {
        "id":1,
        "image":"img/beetroot.jpg",
        "caption":"Beetroot",
        "text": "/ˈbiːtɹuːt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/beetroot-au.mp3",
    },
   
    {
        "id":2,
        "image":"img/broccoli.jpeg",
        "caption":"Broccoli",
        "text": "/ˈbɹɑ.kə.li/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/broccoli-us.mp3",
    },
    {
        "id":3,
        "image":"img/cabbage.jpg",
        "caption":"Cabbage",
        "text": "/ˈkæbɪdʒ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cabbage-uk.mp3",
    },
    {
        "id":4,
        "image":"img/carrot.jpg",
        "caption":"Carrot",
        "text": "/ˈkæɹ.ət/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/carrot-us.mp3",
    },
    {
        "id":5,
        "image":"img/courgette.jpg",
        "caption":"Courgette",
        "text": "/kɔːˈʒɛt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/courgette-uk.mp3",
    },
    {
        "id":6,
        "image":"img/cucumber.jpg",
        "caption":"Cucumber",
        "text": "/ˈkjuːˌkʌmbɚ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cucumber-us.mp3",
    },
    {
        "id":7,
        "image":"img/lettuce.jpg",
        "caption":"Lettuce",
        "text": "/ˈlɛtəs/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/lettuce-us.mp3",
    },
    {
        "id":8,
        "image":"img/onion.jpg",
        "caption":"Onion",
        "text": "/ˈʌnjən/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/onion-uk.mp3",
    },
    {
        "id":9,
        "image":"img/pepper.jpg",
        "caption":"Pepper",
        "text": "/ˈpɛpə/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/pepper-uk.mp3",
    },
    {
        "id":10,
        "image":"img/pumpkin.jpg",
        "caption":"Pumpkin",
        "text": "/ˈpʌmpkɪn/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/pumpkin-au.mp3",
    },
    {
        "id":11,
        "image":"img/radish.jpeg",
        "caption":"Radish",
        "text": "/ˈɹædɪʃ/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/radish-us.mp3",
    },
    {
        "id":12,
        "image":"img/tomato.jpg",
        "caption":"Tomato",
        "text": "[tʰə̥ˈmɑːtʰəʊ]",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/tomato-uk.mp3",
    }
]