let words = [
    {
        "id":1,
        "image":"img/beetroot.jpg",
        "caption":"Beetroot",
    },
    {
        "id":2,
        "image":"img/bell_pepper.jpg",
        "caption":"Bell pepper",
    },
    {
        "id":3,
        "image":"img/broccoli.jpeg",
        "caption":"Broccoli",
    },
    {
        "id":4,
        "image":"img/cabbage.jpg",
        "caption":"Cabbage",
    },
    {
        "id":5,
        "image":"img/courgette.jpg",
        "caption":"Courgette",
    },
    {
        "id":6,
        "image":"img/cucumber.jpg",
        "caption":"Cucumber",
    },
    {
        "id":7,
        "image":"img/eggplant.jpg",
        "caption":"Eggplant",
    },
    {
        "id":8,
        "image":"img/lettuce.jpg",
        "caption":"Lettuce",
    },
    {
        "id":9,
        "image":"img/onion.jpg",
        "caption":"Onion",
    },
    {
        "id":10,
        "image":"img/pumpkin.jpg",
        "caption":"Pumpkin",
    },
    {
        "id":11,
        "image":"img/radish.jpeg",
        "caption":"Radish",
    },
    {
        "id":12,
        "image":"img/tomato.jpg",
        "caption":"Tomato",
    }
]