let words = [
    {
        "id":1,
        "image":"img/cloudy.jpg",
        "caption":"Cloudy",
    },
    {
        "id":2,
        "image":"img/foggy.jpg",
        "caption":"Foggy",
    },
    {
        "id":3,
        "image":"img/gloomy.png",
        "caption":"Gloomy",
    },
    {
        "id":4,
        "image":"img/hailing.jpg",
        "caption":"Hailing",
    },
    {
        "id":5,
        "image":"img/partly_cloudy.jpg",
        "caption":"Partly cloudy",
    },
    {
        "id":6,
        "image":"img/rainy.jpg",
        "caption":"Rainy",
    },
    {
        "id":7,
        "image":"img/sleeting.png",
        "caption":"Sleeting",
    },
    {
        "id":8,
        "image":"img/snowy.png",
        "caption":"Snowy",
    },
    {
        "id":9,
        "image":"img/stormy.jpg",
        "caption":"Stormy",
    },
    {
        "id":10,
        "image":"img/sunny.jpg",
        "caption":"Sunny",
    },
    {
        "id":11,
        "image":"img/thundery.png",
        "caption":"Thundery",
    },
    {
        "id":12,
        "image":"img/windy.jpg",
        "caption":"Windy",
    }
]