let words = [
    {
        "id":1,
        "image":"img/cloudy.jpg",
        "caption":"Cloudy",
        "text": "/ˈkɫaʊdi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cloudy-us.mp3",
    },
    {
        "id":2,
        "image":"img/gloomy.png",
        "caption":"Gloomy",
        "text": "/ˈɡlumi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/gloomy-us.mp3",
    },
    {
        "id":3,
        "image":"img/icy.png",
        "caption":"Icy",
        "text": "/ˈaɪsi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/icy-us.mp3",
    },
    {
        "id":4,
        "image":"img/hailing.jpg",
        "caption":"Hail",
        "text": "/heɪl/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/hail-us.mp3",
    },
    {
        "id":5,
        "image":"img/partly_cloudy.jpg",
        "caption":"Partly cloudy",
        "text": "/ˈkɫaʊdi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/cloudy-us.mp3",
    },
    {
        "id":6,
        "image":"img/rainy.jpg",
        "caption":"Rain",
        "text": "/ɹeɪn/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/rain-uk.mp3",
    },
    {
        "id":7,
        "image":"img/sleeting.png",
        "caption":"Sleet",
        "text": "/sliːt/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/sleet-uk.mp3",
    },
    {
        "id":8,
        "image":"img/snowy.png",
        "caption":"Snowy",
        "text": "/snəʊi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/snowy-us.mp3",
    },
    {
        "id":9,
        "image":"img/stormy.jpg",
        "caption":"Stormy",
        "text": "/ˈstɔɹmi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/stormy-us.mp3",
    },
    {
        "id":10,
        "image":"img/sunny.jpg",
        "caption":"Sunny",
        "text": "/ˈsʌni/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/sunny-us.mp3",
    },
    {
        "id":11,
        "image":"img/thundery.png",
        "caption":"Thunderstorm",
        "text": "/ˈθʌn.də(ɹ)ˌstɔː(ɹ)m/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/thunderstorm-ca.mp3",
    },
    {
        "id":12,
        "image":"img/windy.jpg",
        "caption":"Windy",
        "text": "/ˈwɪndi/",
        "audio": "https://api.dictionaryapi.dev/media/pronunciations/en/windy-1-au.mp3",
    }
]